#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
  groupadd -r thingsplex || true
  groupadd -r glamox || true

  useradd -r -N -M -d / -s /bin/false -g thingsplex glamox || true

  chown -R glamox:thingsplex /var/log/thingsplex/glamox/ || true
  chown -R glamox:glamox /opt/thingsplex/glamox/ || true
fi

deb-systemd-helper unmask glamox.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled glamox.service; then
  systemctl enable glamox.service || true
else
  deb-systemd-helper update-state glamox.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true

  if [ -n "$2" ]; then
    deb-systemd-invoke try-restart glamox.service >/dev/null || true
  else
    deb-systemd-invoke start glamox.service >/dev/null || true
  fi
fi