#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop glamox.service >/dev/null
  systemctl disable glamox.service || true
  rm -r /var/log/thingsplex/glamox/ || true
  rm -r /opt/thingsplex/glamox/data/ || true
fi