#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop adax.service >/dev/null
  systemctl disable adax.service || true
  rm -r /var/log/thingsplex/adax/ || true
  rm -r /opt/thingsplex/adax/data/ || true
fi